CREATE TABLE IF NOT EXISTS temperatura (
    id INT AUTO_INCREMENT PRIMARY KEY,
    graus FLOAT,
    data DATETIME
);

CREATE TABLE IF NOT EXISTS sensor (
    id INT AUTO_INCREMENT PRIMARY KEY,
    bateria FLOAT,
    data DATETIME
);